Made a mistake when trying to fix deno url
drashland/deno-drash pull request #407
Opened 2020-10-27 19:01 UTC by MVEMCJSUNPE

The official repo name was drashland/deno-drash,
but for some reason, I wrote drashland/deno-land.
My bad.

Fixes [#403 ]

**Description**

2020-10-27 19:04 UTC, ebebbington requested changes
It was my bad, it got past code review

2020-10-27 19:04 UTC, ebebbington commented on tests/cli/create_app_test_http.ts
> +        console.log(`${testCaseTmpDirName}`);
Just need to remove the debugging line :)

2020-10-27 19:05 UTC, ebebbington commented
@MVEMCJSUNPE you will need to uncomment the block from `.github/workflows/master.yml` to ensure the create app http tests work too

2020-10-27 19:17 UTC, MVEMCJSUNPE commented
Didn't notice those. Thanks! Is there a way to run tests in releases.yml locally?

2020-10-27 19:19 UTC, ebebbington commented
> Didn't notice those. Thanks! Is there a way to run tests in releases.yml locally?

https://github.com/nektos/act BUT it doesn't work with deno, i've tried and tested it and raised an issue, might work with simpler workflow files

2020-10-27 19:19 UTC, ebebbington commented on .github/workflows/master.yml
> +      Commented out since this doesn't work on forks of main repository
Just need to remove this line ;)

2020-10-27 19:53 UTC, ebebbington commented on .github/workflows/master.yml
> +      Commented out since this doesn't work on forks of main repository
unresolving

2020-10-27 21:53 UTC, ebebbington commented on .github/workflows/master.yml
> +      Commented out since this doesn't work on forks of main repository
No you have to make the code change yourself and commit it, the reviewing on GH is just a way to highlight code in a PR and comment in it

2020-10-27 21:55 UTC, ebebbington commented
@MVEMCJSUNPE the http tests seem to still be pulling through the drashland/deno-drash repo (and thus failing):

![image](https://user-images.githubusercontent.com/47337480/97366342-11a7ac00-189f-11eb-83a7-0a8ef609456c.png)

2020-10-27 21:58 UTC, ebebbington commented
Seems the `githubRepo` is not defined, or the value it's assigned is the drashland repo, you could try logging out the details in the test, which i. funily enough asked to remove earlier, i'm guessing you left it in to debug, but i forgot :P

2020-10-28 01:02 UTC, MVEMCJSUNPE commented
With the latest commit, I think we can be sure that githubRepo is simply being assigned to the drashland repo.

2020-10-28 05:33 UTC, crookse commented
> With the latest commit, I think we can be sure that githubRepo is simply being assigned to the drashland repo.

so just for future reference, the only modules allowed in deno-drash, rhum, dmm, dawn, and sockets are deno std modules or drashland modules. i see you've added octokit. is there a reason why a `fetch()` call can't be used to see if a URL to a branch returns a 404 status code?

2020-10-28 15:29 UTC, MVEMCJSUNPE commented
I guess I was just lazy. When I tried "https://raw.githubusercontent.com/drashland/deno-drash/master", it would give me a 404 error. While could try "https://raw.githubusercontent.com/drashland/deno-drash/master/create_app.ts" that seems kind of iffy to me: if a filename gets changed or remove, how would we know the difference between whether the repository not existing or the file not existing on the repository due to major changes?

2020-10-28 15:32 UTC, crookse commented
that's why we have acceptance criteria and tests to cover the codebase and cases like this in the CI. if we change the create_app script name, then it will break the integration tests in the CI. there's currently work being done to move the create app script into a drash CLI, and if it's not handled properly in all places in the codebase then the CI will fail

2020-10-28 16:37 UTC, MVEMCJSUNPE commented
For some reason, it's working on my computer:
<img width="950" alt="create_app_success" src="https://user-images.githubusercontent.com/10354503/97467129-df836200-1911-11eb-8481-7923a65b23f2.png">

2020-10-28 16:39 UTC, ebebbington commented on tests/cli/create_app_test_http.ts
> +  drashUrl = "https://raw.githubusercontent.com/drashland/deno-drash/master";
Race condition here probably, do:
```
try {
  await fetch(drashUrl + "/create_app.ts")
} catch (err) {
  drashUrl = ...
}
```

2020-10-28 16:40 UTC, ebebbington commented
But it's probably failing due to the env vars inside the GH runner

2020-10-28 17:37 UTC, ebebbington commented
Oh ok cause this PR is under drashland, the GH runner env vars are pointing to this repo

2020-10-28 17:50 UTC, ebebbington commented
@MVEMCJSUNPE can you add:
```
console.log("START")
console.log(latestBranch)
console.log(githubRepo)
console.log("END")
```
Below line 15ish in `tests/cli/create_app_http_test.ts` and push it up?

2020-10-28 17:54 UTC, ebebbington commented
Maybe we could do something like `const url = 'GITHUB OWNER + "deno-drash" + GITHUB_BRANCH'`

2020-10-28 19:09 UTC, MVEMCJSUNPE commented
By "GITHUB OWNER" and "GITHUB_BRANCH", are you talking about environment variables? I checked Github's [environment variables](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables), and I couldn't find those variables.

2020-10-28 19:10 UTC, ebebbington commented
> By "GITHUB OWNER" and "GITHUB_BRANCH", are you talking about environment variables? I checked Github's [environment variables](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables), and I couldn't find those variables.

Yeeah it was more pseudo code, i'm not sure how we'd do that bit tho, i need to think it through

2020-10-28 19:13 UTC, ebebbington commented
@MVEMCJSUNPE could you also add `console.log(Deno.env.get("GITHUB_OWNER")` too if that's ok? Sorry if i'm bugging you

I'm thinking we could do:
```
const url = `${Deno.env.get("GITHUB_OWNER")}/deno-drash/${Deno.env.get("GITHUB_REPOSITORY")}`
```

2020-10-28 19:16 UTC, MVEMCJSUNPE commented
I think BASE_REF looks pretty promising. Maybe I'll just use that for latestBranch.

2020-10-28 19:20 UTC, ebebbington commented
GITHUB_BASE_REF would always be master i believe, see [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#:~:text=Environment%20variables%20are%20case%2Dsensitive,entire%20workflow%20using%20the%20jobs.)

2020-10-28 19:30 UTC, MVEMCJSUNPE commented
I think we should just accept that there's no way to get the repository ("MVEMCJSUNPE/deno-drash") of whoever forked from the main repository (drashland/deno-drash). Since this is the case, the environment variable "GITHUB_HEAD_REF" won't ever work for forked repos.

2020-10-28 19:31 UTC, ebebbington commented
So i guess, all the getting of the repo logic could just be:
```
// supports forks
let drashUrl = "https://raw.githubusercontent.com/" + Deno.env.get("GITHUB_OWNER") +
  `/deno-drash/${latestBranch}`; // https://raw.githubusercontent.com/<NAME>/deno-drash/<branch>

// if fork doesnt exist, use drashland repo, eg name might be ebebbington, but i dont have a fork
try {
  const res = await fetch(drashurl)
  await res.json()
  if (res.status !== 200) {
    drashUrl = "https://raw.githubusercontent.com/drashland" +
  `/deno-drash/${latestBranch}
} catch (err) {
  // do nothing
}
```

2020-10-28 19:46 UTC, crookse commented
i'm going to investigate this as well

2020-10-28 20:11 UTC, ebebbington commented
@MVEMCJSUNPE using your help, i managed to get it working :D #410

2020-10-28 20:12 UTC, MVEMCJSUNPE commented
How'd I help?

2020-10-28 20:14 UTC, MVEMCJSUNPE commented
I got it to work again locally, but the CI tests just keep saying no.

2020-10-30 22:36 UTC, closed without merging